version: '3.7'

services:
  app:
    image: chaosdorf/chaospizza:latest
    environment:
      - DJANGO_ALLOWED_HOSTS=pizza.chaosdorf.space
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - DJANGO_DATABASE_URL=postgresql://chaospizza:chaospizza@db:5432/chaospizza
    secrets:
      - source: CHAOSPIZZA_DJANGO_SECRET_KEY
        target: DJANGO_SECRET_KEY
      - source: CHAOSPIZZA_SENTRY_DSN
        target: SENTRY_DSN
    networks:
      - internal
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.125'
          memory: 64M
      labels:
        - traefik.swarm.network=traefik_net
        - traefik.http.services.chaospizza.loadbalancer.server.port=8000
        - "traefik.http.routers.chaospizza.rule=Host(`pizza.chaosdorf.space`)"
        - traefik.http.routers.chaospizza.middlewares=global-headers@file,chaospizza-error@swarm
        - traefik.http.routers.chaospizza.service=chaospizza@swarm
        - traefik.http.routers.chaospizza.tls=true
        - traefik.http.routers.chaospizza.tls.certresolver=default
        - traefik.http.routers.chaospizza.tls.domains[0].main=*.chaosdorf.space
        - traefik.http.middlewares.chaospizza-error.errors.service=error@swarm
        - traefik.http.middlewares.chaospizza-error.errors.status=401,403,404,429,500,503
        - traefik.http.middlewares.chaospizza-error.errors.query=/{status}.html
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: chaospizza
      POSTGRES_PASSWORD: chaospizza
      POSTGRES_DB: chaospizza
    volumes:
      - database2:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.125'
          memory: 16M
  db-backup:
    image: quay.io/chaosdorf/postgres-backup:latest
    volumes:
      - backup:/backup
    networks:
      - internal
    environment:
      PGUSER: chaospizza
      PGPASSWORD: chaospizza
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5

volumes:
  database2:
  backup:

networks:
  internal:
    driver: overlay
  traefik:
    driver: overlay
    external: true
    name: traefik_net

secrets:
  CHAOSPIZZA_SENTRY_DSN:
    external: true
  CHAOSPIZZA_DJANGO_SECRET_KEY:
    external: true
