version: '3.7'

services:
  db:
    image: tianon/postgres-upgrade:9.6-to-13
    environment:
      PGUSER: chaospizza
      PGPASSWORD: chaospizza
      POSTGRES_INITDB_ARGS: --username=chaospizza --pwfile=<(echo chaospizza)
    volumes:
      - database:/var/lib/postgresql/9.6/data
      - database2:/var/lib/postgresql/13/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

volumes:
  database:
  database2:
  backup:

networks:
  internal:
    driver: overlay
  traefik:
    driver: overlay
    external: true
    name: traefik_net

secrets:
  CHAOSPIZZA_SENTRY_DSN:
    external: true
  CHAOSPIZZA_DJANGO_SECRET_KEY:
    external: true
