version: '3.7'

services:
  db:
    image: hello-world
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

volumes:
  database:
  backup:

networks:
  internal:
    driver: overlay
  traefik:
    driver: overlay
    external: true
    name: traefik_net

secrets:
  CHAOSPIZZA_SENTRY_DSN:
    external: true
  CHAOSPIZZA_DJANGO_SECRET_KEY:
    external: true
