version: '3.7'

services:
  app:
    image: chaosdorf/dashpi:latest
    environment:
      - TRAFFIC_HOST=feedback.chaosdorf.space
      - MOSQUITTO_HOST=mqttserver.chaosdorf.space
      - PING_HOST=speedtest-2.unitymedia.de
    secrets:
      - DASHING_AUTH_TOKEN
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - source: DASHPI_SENTRY_DSN
        target: SENTRY_DSN
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      update_config:
        order: start-first
      labels:
        - traefik.swarm.network=traefik_net
        - traefik.http.services.dashpi.loadbalancer.server.port=3030
        - "traefik.http.routers.dashpi-http.rule=Host(`dashboard.chaosdorf.space`) || Host(`dashboard`)"
        - traefik.http.routers.dashpi-http.middlewares=global-headers@file
        - traefik.http.routers.dashpi-http.service=dashpi@swarm
        - "traefik.http.routers.dashpi-https.rule=Host(`dashboard.chaosdorf.space`) || Host(`dashboard`)"
        - traefik.http.routers.dashpi-https.middlewares=global-headers@file
        - traefik.http.routers.dashpi-https.service=dashpi@swarm
        - traefik.http.routers.dashpi-https.tls=true
        - traefik.http.routers.dashpi-https.tls.certresolver=default
        - traefik.http.routers.dashpi-https.tls.domains[0].main=*.chaosdorf.space
networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net

secrets:
  DASHING_AUTH_TOKEN:
    external: true
  TWITTER_ACCESS_TOKEN:
    external: true
  TWITTER_ACCESS_TOKEN_SECRET:
    external: true
  TWITTER_CONSUMER_KEY:
    external: true
  TWITTER_CONSUMER_SECRET:
    external: true
  DASHPI_SENTRY_DSN:
    external: true
