version: '3.7'
services:
  app:
    image: marudor/dorfmap-websockets:latest
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.125'
          memory: 16M
      labels:
        - traefik.docker.network=traefik_net
        - traefik.http.services.dorfmapserver.loadbalancer.server.port=3001
        - "traefik.http.routers.dorfmapserver-http.rule=Host(`dorfmapserver.chaosdorf.space`) || Host(`dorfmapserver`)"
        - traefik.http.routers.dorfmapserver-http.middlewares=global-headers@file
        - traefik.http.routers.dorfmapserver-http.service=dorfmapserver@docker
        - "traefik.http.routers.dorfmapserver-https.rule=Host(`dorfmapserver.chaosdorf.space`) || Host(`dorfmapserver`)"
        - traefik.http.routers.dorfmapserver-https.middlewares=global-headers@file
        - traefik.http.routers.dorfmapserver-https.service=dorfmapserver@docker
        - traefik.http.routers.dorfmapserver-https.tls=true
        - traefik.http.routers.dorfmapserver-https.tls.certresolver=default
        - traefik.http.routers.dorfmapserver-https.tls.domains[0].main=*.chaosdorf.space
networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net
