version: '3.7'

services:
  app:
    image: guillaumebriday/traefik-custom-error-pages:latest
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
        reservations:
          cpus: '0.125'
          memory: 5M
      labels:
        - traefik.docker.network=traefik_net
        - traefik.http.services.error.loadbalancer.server.port=80
        - "traefik.http.routers.error.rule=HostRegexp(`{host:.+}`)"
        - traefik.http.routers.error.priority=1 # low priority as fallback

networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net
