version: '3.7'

services:
  app:
    image: chaosdorf/freitagsfoo-web:latest
    secrets:
      - INFO_BEAMER_API_KEY
      - FFTALKS_SENTRY_DSN
    configs:
      - source: toml3
        target: /etc/freitagsfoo-web.toml
    networks:
      - traefik
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      labels:
        - traefik.docker.network=traefik_net
        - traefik.http.services.fftalks.loadbalancer.server.port=5000
        - "traefik.http.routers.fftalks-http.rule=Host(`fftalks.chaosdorf.space`) || Host(`fftalks`)"
        - traefik.http.routers.fftalks-http.middlewares=global-headers@file,fftalks-error@docker
        - traefik.http.routers.fftalks-http.service=fftalks@docker
        - "traefik.http.routers.fftalks-https.rule=Host(`fftalks.chaosdorf.space`) || Host(`fftalks`)"
        - traefik.http.routers.fftalks-https.middlewares=global-headers@file,fftalks-error@docker
        - traefik.http.routers.fftalks-https.service=fftalks@docker
        - traefik.http.routers.fftalks-https.tls=true
        - traefik.http.routers.fftalks-https.tls.certresolver=default
        - traefik.http.routers.fftalks-https.tls.domains[0].main=*.chaosdorf.space
        - traefik.http.middlewares.fftalks-error.errors.service=error@docker
        - traefik.http.middlewares.fftalks-error.errors.status=401,403,429,503
        - traefik.http.middlewares.fftalks-error.errors.query=/{status}.html
  redis:
    image: redis:6-alpine
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5

networks:
  internal:
    driver: overlay
  traefik:
    driver: overlay
    external: true
    name: traefik_net

secrets:
  INFO_BEAMER_API_KEY:
    external: true
  FFTALKS_SENTRY_DSN:
    external: true

configs:
  toml3:
    file: ../configs/fftalks.toml
