version: '3.7'

services:
  app:
    image: chaosdorf/labello:latest
    secrets:
      - source: LABELLO_SENTRY_DSN
        target: SENTRY_DSN
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 32M
      labels:
        - traefik.docker.network=traefik_net
        - traefik.port=8000
        - traefik.frontend.rule=Host:labello.chaosdorf.space,labello

networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net

secrets:
  LABELLO_SENTRY_DSN:
    external: true
