version: '3.7'

services:
  app:
    image: hello-world
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
  db:
    image: busybox:1.34
    command: ["sh", "-c", "echo 'host all all all md5' >> /database/pg_hba.conf"]
    volumes:
      - database2:/database
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
  db-backup:
    image: hello-world
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

volumes:
  system:
  database:
  database2:
  backup:

networks:
  internal:
    driver: overlay
  traefik:
    driver: overlay
    external: true
    name: traefik_net

secrets:
  METE_SENTRY_DSN:
    external: true
