version: '3.7'

services:
  app:
    image: chaosdorf/mete:latest
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=yoloyolo123
    secrets:
      - source: METE_SENTRY_DSN
        target: SENTRY_DSN
    volumes:
      - system:/app/public/system
    networks:
      - internal
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      labels:
        - traefik.docker.network=traefik_net
        - traefik.port=80
        - traefik.frontend.rule=Host:mete.chaosdorf.space,mete
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: mete
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
  db-backup:
    image: nomaster/postgres-backup
    environment:
      PGPASSWORD: mete
    volumes:
      - backup:/backup
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5

volumes:
  system:
  database:
  backup:

networks:
  internal:
    driver: overlay
  traefik:
    driver: overlay
    external: true
    name: traefik_net

secrets:
  METE_SENTRY_DSN:
    external: true
