version: '3.7'

services:
  app:
    image: chaosdorf/mete:latest
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=yoloyolo123
    secrets:
      - source: METE_SENTRY_DSN
        target: SENTRY_DSN
    volumes:
      - system:/app/public/system
    networks:
      - internal
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      labels:
        - traefik.docker.network=traefik_net
        - traefik.http.services.mete.loadbalancer.server.port=80
        - "traefik.http.routers.mete-http.rule=Host(`mete.chaosdorf.space`) || Host(`mete`)"
        - traefik.http.routers.mete-http.middlewares=global-headers@file
        - traefik.http.routers.mete-http.service=mete@docker
        - "traefik.http.routers.mete-https.rule=Host(`mete.chaosdorf.space`) || Host(`mete`)"
        - traefik.http.routers.mete-https.middlewares=global-headers@file
        - traefik.http.routers.mete-https.service=mete@docker
        - traefik.http.routers.mete-https.tls=true
        - traefik.http.routers.mete-https.tls.certresolver=default
        - traefik.http.routers.mete-https.tls.domains[0].main=*.chaosdorf.space
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: mete
    volumes:
      - database2:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
  db-backup:
    image: nomaster/postgres-backup
    environment:
      PGPASSWORD: mete
    volumes:
      - backup:/backup
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5

volumes:
  system:
  database2:
  backup:

networks:
  internal:
    driver: overlay
  traefik:
    driver: overlay
    external: true
    name: traefik_net

secrets:
  METE_SENTRY_DSN:
    external: true
