version: '3.7'

services:
  app:
    image: chaosdorf/mpd-mqtt-gateway:latest
    secrets:
      - source: MPD2MQTT_SENTRY_DSN
        target: SENTRY_DSN
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  MPD2MQTT_SENTRY_DSN:
    external: true
