version: '3.7'

services:
  app:
    image: telegnom/labello:latest
    environment:
      - LAB_SERVER_PORT=8000
      - LAB_SERVER_HOST=0.0.0.0
      - LAB_LOGGING=30
      - LAB_WEBSITE_HTML_TITLE=prittstift - more than labello
      - LAB_WEBSITE_TITLE=prittstift
      - LAB_WEBSITE_SLUG=labello++
      - LAB_WEBSITE_BOOTSTRAP_LOCAL=True
      - LAB_LABEL_MARGIN_TOP=24
      - LAB_LABEL_MARGIN_BOTTOM=24
      - LAB_LABEL_MARGIN_LEFT=24
      - LAB_LABEL_MARGIN_RIGHT=24
      - LAB_LABEL_FEED_MARGIN=16
      - LAB_LABEL_FONT_SPACING=13
      - LAB_PRINTER_DEVICE=tcp://10.1.255.228:9100
      - LAB_PRINTER_MODEL=QL-720NW
      - LAB_FONT_PATH=/opt/labello/fonts
    networks:
      - traefik
    volumes:
      - fonts:/opt/labello/fonts
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.125'
          memory: 16M
      labels:
        - traefik.docker.network=traefik_net
        - traefik.http.services.prittstift.loadbalancer.server.port=8000
        - "traefik.http.routers.prittstift-http.rule=Host(`prittstift.chaosdorf.space`) || Host(`prittstift`)"
        - traefik.http.routers.prittstift-http.middlewares=global-headers@file,prittstift-error@docker
        - traefik.http.routers.prittstift-http.service=prittstift@docker
        - "traefik.http.routers.prittstift-https.rule=Host(`prittstift.chaosdorf.space`) || Host(`prittstift`)"
        - traefik.http.routers.prittstift-https.middlewares=global-headers@file,prittstift-error@docker
        - traefik.http.routers.prittstift-https.service=prittstift@docker
        - traefik.http.routers.prittstift-https.tls=true
        - traefik.http.routers.prittstift-https.tls.certresolver=default
        - traefik.http.routers.prittstift-https.tls.domains[0].main=*.chaosdorf.space
        - traefik.http.middlewares.prittstift-error.errors.service=error@docker
        - traefik.http.middlewares.prittstift-error.errors.status=401,403,404,429,500,503
        - traefik.http.middlewares.prittstift-error.errors.query=/{status}.html

networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net

volumes:
  fonts:
