version: '3.7'

services:
  app:
    image: chaosdorf/pawebcontrol:latest
    environment:
      - PULSE_SERVER=pulse.chaosdorf.space
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 32M
        reservations:
          cpus: '0.25'
          memory: 8M
      labels:
        - traefik.docker.network=traefik_net
        - traefik.port=8000
        - traefik.frontend.rule=Host:pulseweb.chaosdorf.space,pulseweb

networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net
