version: '3.7'

services:
  app:
    image: chaosdorf/siamqtt:latest
    configs:
      - source: config2
        target: /etc/siamqtt.toml
    secrets:
      - SIAMQTT_SENTRY_DSN
    ports:
      - published: 1001
        target: 1001
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5

configs:
  config2:
    file: ../configs/siamqtt.toml

secrets:
  SIAMQTT_SENTRY_DSN:
    external: true
