version: "3.7"

volumes:
  prometheus:

networks:
  internal:
  dashpi_internal:
    external: true

configs:
  snmp:
    file: ../configs/snmp.yml
  prometheus:
    file: ../configs/prometheus.yml

services:
  exporter:
    image: prom/snmp-exporter
    configs:
      - source: snmp
        target: /etc/snmp_exporter/snmp.yml
    ports:
      - 9116
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
  prometheus:
    image: prom/prometheus
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus:/prometheus
    networks:
      - internal
      - dashpi_internal
    ports:
      - 9090
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
