version: '3.7'

services:
  app:
    image: chaosdorf/spacebell:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      update_config:
        order: start-first
    environment:
      PULSE_SERVER: pulse.chaosdorf.space
