version: '3.7'

services:
  proxy:
    image: traefik:v1.7
    environment:
      CF_API_EMAIL: account+cloudflare@chaosdorf.de
      CF_API_KEY_FILE: /run/secrets/CF_API_KEY
    configs:
      - source: toml
        target: /etc/traefik/traefik.toml
    secrets:
      - CF_API_KEY
      - TRAEFIK_DIGEST_AUTH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/traefik/acme
      - tmp:/tmp
    networks:
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 32M
      labels:
        - traefik.docker.network=traefik_net
        - traefik.port=8080
        - traefik.frontend.rule=Host:traefik.chaosdorf.space,traefik
        - traefik.frontend.entryPoints=https

volumes:
  acme:
  tmp:

networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net

configs:
  toml:
    file: ../configs/traefik.toml

secrets:
  CF_API_KEY:
    external: true
  TRAEFIK_DIGEST_AUTH:
    external: true
