version: '3.7'

services:
  app:
    image: chaosdorf/ympd:latest
    environment:
      - MPD_SERVER=mpd.chaosdorf.space
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=traefik_net
        - traefik.port=8080
        - traefik.frontend.rule=Host:ympd.chaosdorf.space

networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net
