[INFO-BEAMER]
pi-id = 21405
background-setup-id = 9428
background-setup-name = "31c3"
talks-setup-id = 10146
talks-setup-name = "Freitagsfoo"
extron-port = 6

[REDIS]
URL = "redis://redis:6379/0"

[EXTRON]
url = "http://videomix/"
num-inputs = 6
