[http.middlewares]
  [http.middlewares.global-headers.headers]
     STSSeconds=2592000
     [http.middlewares.global-headers.headers.customResponseHeaders]
      Permissions-Policy="interest-cohort=()"
