version: '3.7'

services:
  app:
    image: portainer/portainer:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - app-data:/data
    networks:
      - internal
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 60s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 32M
      labels:
        - traefik.swarm.network=traefik_net
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - "traefik.http.routers.portainer-http.rule=Host(`portainer.chaosdorf.space`) || Host(`portainer`)"
        - traefik.http.routers.portainer-http.middlewares=global-headers@file,portainer-error@swarm
        - traefik.http.routers.portainer-http.service=portainer@swarm
        - "traefik.http.routers.portainer-https.rule=Host(`portainer.chaosdorf.space`) || Host(`portainer`)"
        - traefik.http.routers.portainer-https.middlewares=global-headers@file,portainer-error@swarm
        - traefik.http.routers.portainer-https.service=portainer@swarm
        - traefik.http.routers.portainer-https.tls=true
        - traefik.http.routers.portainer-https.tls.certresolver=default
        - traefik.http.routers.portainer-https.tls.domains[0].main=*.chaosdorf.space
        - traefik.http.middlewares.portainer-error.errors.service=error@swarm
        - traefik.http.middlewares.portainer-error.errors.status=401,403,404,429,500,503
        - traefik.http.middlewares.portainer-error.errors.query=/{status}.html
  agent:
    image: portainer/agent:latest
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - internal
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 32M

volumes:
  app-data:

networks:
  internal:
    driver: overlay
  traefik:
    driver: overlay
    external: true
    name: traefik_net
